spring.application.name=marketplace

# Docker
spring.docker.compose.lifecycle-management=start_and_stop

# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
application.security.jwt.secret-key=75521930cce7c2ff734f6dd65b67ec3b8bc61ae2a8c1fa7a19f134ee12d0d5bb
application.security.jwt.access-token-expiration=3600000
application.security.jwt.refresh-token-expiration=604800000

# File Upload
file.upload-dir=uploads